name: Teams Notification

description: Send Microsoft Teams notifications for pipeline results

inputs:
  teams-webhook:
    description: Microsoft Teams webhook
    required: true
  pipeline-status:
    description: Pipeline status ("success", "failure", etc.)
    required: true
  job-context:
    description: Source job (e.g., compile-app or publish-app)
    required: true
  repository:
    description: GitHub repository
    default: ${{ github.repository }}
  pull-number:
    description: Pull request number
    default: ${{ github.event.pull_request.number }}
  ref-name:
    description: GitHub branch name
    default: ${{ github.ref_name }}
  actor:
    description: Triggered by (actor)
    default: ${{ github.actor }}
  commit-message:
    description: Commit message
    default: ${{ github.event.head_commit.message }}
  run-id:
    description: Workflow run ID
    default: ${{ github.run_id }}
  environment:
    description: Target BC environment (optional)
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Teams Notification
      shell: bash
      run: |
        BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}"

        if [ "${{ inputs.pipeline-status }}" = "success" ]; then
          if [ "${{ inputs.job-context }}" = "compile-app" ]; then
            title="Compilation Successful"
            summary="AL application compiled and tested successfully."
          elif [ "${{ inputs.job-context }}" = "publish-app" ]; then
            title="Publish Successful"
            summary="App successfully published to ${{ inputs.environment }}."
          else
            title="Success"
            summary="Pipeline completed successfully."
          fi
          color="00FF00"

        elif [ "${{ inputs.pipeline-status }}" = "failure" ]; then
          if [ "${{ inputs.job-context }}" = "compile-app" ]; then
            title="Compilation Failed"
            summary="Compilation failed during code analysis or unit tests."
          elif [ "${{ inputs.job-context }}" = "publish-app" ]; then
            title="Publish Failed"
            summary="Publish failed to ${{ inputs.environment }}."
          else
            title="Pipeline Failed"
            summary="Pipeline failed."
          fi
          color="FF0000"

        else
          title="Pipeline Status"
          summary="Pipeline status: ${{ inputs.pipeline-status }}"
          color="CCCCCC"
        fi

        payload=$(jq -n \
          --arg title "$title" \
          --arg summary "$summary" \
          --arg color "$color" \
          --arg repo "${{ inputs.repository }}" \
          --arg branch "$BRANCH_NAME" \
          --arg actor "${{ inputs.actor }}" \
          --arg commit "${{ inputs.commit-message }}" \
          --arg prText "View PR" \
          --arg prUrl "https://github.com/${{ inputs.repository }}/pull/${{ inputs.pull-number }}" \
          --arg runText "View Run" \
          --arg runUrl "https://github.com/${{ inputs.repository }}/actions/runs/${{ inputs.run-id }}" \
          '{
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "contentUrl": null,
                "content": {
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "type": "AdaptiveCard",
                  "version": "1.2",
                  "body": [
                    { "type": "TextBlock", "size": "Large", "weight": "Bolder", "color": "Good", "text": $title },
                    { "type": "TextBlock", "text": $summary, "wrap": true },
                    { "type": "FactSet", "facts": [
                      { "title": "Repository:", "value": $repo },
                      { "title": "Branch:", "value": $branch },
                      { "title": "Actor:", "value": $actor },
                      { "title": "Commit:", "value": $commit }
                    ]},
                    {
                      "type": "ColumnSet",
                      "columns": [
                        {
                          "type": "Column",
                          "width": "stretch",
                          "items": [
                            {
                              "type": "TextBlock",
                              "text": "[View Run](https://github.com/${{ inputs.repository }}/actions/runs/${{ inputs.run-id }})",
                              "wrap": true,
                              "spacing": "Medium"
                            }
                          ]
                        },
                        {
                          "type": "Column",
                          "width": "stretch",
                          "items": [
                            {
                              "type": "TextBlock",
                              "text": "[View PR](https://github.com/${{ inputs.repository }}/pull/${{ inputs.pull-number }})",
                              "wrap": true,
                              "spacing": "Medium"
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              }
            ]
          }')

        curl -H "Content-Type: application/json" -d "$payload" "${{ inputs.teams-webhook }}"
